CREATE TABLE IF NOT EXISTS books (
    r_id INT AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(36) NOT NULL,
    b_id INT NOT NULL,
    book_name VARCHAR(255) NOT NULL,
    cover_url VARCHAR(512) NOT NULL DEFAULT '',
    book_type VARCHAR(100) NOT NULL DEFAULT '',
    tags TEXT,
    like_num INT NOT NULL DEFAULT 0,
    collect_num INT NOT NULL DEFAULT 0,
    comment_num INT NOT NULL DEFAULT 0,
    comment_long_num INT NOT NULL DEFAULT 0,
    tap_num INT NOT NULL DEFAULT 0,
    monthly_pass INT NOT NULL DEFAULT 0,
    monthly_ticket_ranking INT NOT NULL DEFAULT 0,
    reward_ranking INT NOT NULL DEFAULT 0,
    created_time DATE NOT NULL,
    last_update_time DATE NOT NULL,
    label_type VARCHAR(255) NOT NULL DEFAULT '',
    word_count INT NOT NULL DEFAULT 0,
    finish INT NOT NULL DEFAULT 0,
    INDEX idx_b_id (b_id),
    INDEX idx_created_time (created_time),
    INDEX idx_last_update_time (last_update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
